steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=docker/Dockerfile.firestore
      - --tag=${_IMAGE}
      - .
  - name: gcr.io/cloud-builders/docker
    args: ['push', '${_IMAGE}']
images:
  - '${_IMAGE}'

